name: space_shooter_flutter_flame
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.23.0
  flutter_riverpod: ^2.6.1
  flame_riverpod: ^5.4.7
  equatable: ^2.0.7
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
